version: '3'

networks:
    nginx-php74-mysql8-node:

services:
    nginx:
        build:
            context: ../backend/.docker/nginx
        volumes:
            - ../backend:/app
        container_name: ${PROJECT_NAME}-nginx
        restart: always
        ports:
            - "8080:80"

    php-fpm:
        build:
            context: ../backend/.docker/php-fpm
        volumes:
            - ../backend:/app
        container_name: ${PROJECT_NAME}-php-fpm
        depends_on:
            - mysql
        environment:
            - DB_HOST
            - DB_PORT
            - DB_NAME
            - DB_USER
            - DB_PASSWORD
            - APP_ENV
            - APP_DEBUG


    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - mysql:/var/lib/mysql
        container_name: ${PROJECT_NAME}-mysql
        restart: always
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        ports:
            - "44306:3306"

    # node
    node-service:
        image: node:latest
        container_name: node-container
        volumes:
            - ../backend:/app
        working_dir: /app
        networks:
            - nginx-php74-mysql8-node

volumes:
    mysql: